--- # outline to playbook transliation
- hosts: local
  user: ansible
  become: yes
  gather_facts: no
  tasks:
  - name: date/stamp for when the playbook started
    command: /usr/bin/date
    register: timestamp_start
  - debug: var=timestamp_start
  - name: Install apache webserver
    yum:
      name: httpd
      state: present
    notify: restart_httpd
  - name: Verify that the web service is running
    command: service httpd status
    register: result
  - debug: var=result
  - name: install client software
    yum:
      name: telnet
      state: present
  - name: install tree
    yum:
      name: tree
      state: present
  - name: log all installed packages
    comand: yum list installed
    register: installed.log
  - debug: var=installed.log
  - name: date/time stamp when playbook ends
    command: /usr
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
~
-- INSERT --                                                                                                                                          33,18         All

