---
- hosts: all
  become: yes
  tasks: 
  # java-1.8.0-openjdk.x86_64
  # http://ftp-chi.osuosl.org/pub/jenkins/war-stable/2.60.1/jenkins.war
  - name: install open jdk 8
    yum:
      name: java-1.8.0-openjdk.x86_64
      state: present
  - name: just checking group varibale
    debug:
      msg: "{{log_folder}}"
  - name: just checking host vars
    debug:
      msg: "{{log}}"
  - name: install tomcat7
    yum: 
      name: tomcat
      state: absent    
