---
- hosts: all
  become: yes
  tasks: 
  - name: To know whoami
    command: whoami
  - name: ping all
    ping:
  - name: current directory
    command: pwd
  - name: uninstall tree
    yum:
      name: tree
      state: absent
